### ISSUE TITLE
Routes Data for Healthy People

### ISSUE THREAD

**Issue by rickypinci** [ThisIsIsaac/COVID-19_Korea_Dataset#20]
**Please describe the dataset you want**
Would it be possible to have Routes data also for healthy people (not only for people that got infected)? If that is not possible, do you know if that type of data is available somewhere else?

**How is it relevant to Covid-19?**
Knowing the routes of healthy people may enable interesting comparisons between healthy people and patients.

Thanks for your help.

**Comment by ThisIsIsaac** [comment]
The route data is created by analyzing individual patient's phone GPS locations, card history, and close-circuit cameras. It's an extremely burdensome process to create, and the data itself is very sensitive. So I would say, definitely not, at least not in South Korea. But the patients' routes are essentially similar to healthy citizens', since the patients who've traveled outside have not yet been tested and identified with COVID-19. There may be some bias from the early symptoms of COVID, but I think it's a very close approximation.
